CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE TYPE deal_desk AS ENUM ('agri_food', 'industrial_distribution', 'construction_supply');
CREATE TYPE approval_status AS ENUM ('pending', 'approved', 'rejected', 'executed', 'failed');

CREATE TABLE tenants (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE companies (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenants(id), name text NOT NULL, website text, region text, metadata jsonb NOT NULL DEFAULT '{}');
CREATE INDEX companies_tenant_name_idx ON companies(tenant_id, name);
CREATE TABLE people (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenants(id), company_id uuid REFERENCES companies(id), name text, role text, contact jsonb NOT NULL DEFAULT '{}');
CREATE TABLE sources (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenants(id), url text NOT NULL, name text NOT NULL, source_type text NOT NULL, verified_opportunity_count integer NOT NULL DEFAULT 0, deal_count integer NOT NULL DEFAULT 0, last_checked_at timestamptz, UNIQUE(tenant_id, url));
CREATE TABLE signals (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenants(id), source_id uuid REFERENCES sources(id), desk deal_desk NOT NULL, intent text NOT NULL CHECK (intent IN ('demand','supply','partner')), headline text NOT NULL, market text NOT NULL, source_url text NOT NULL, published_at timestamptz, raw jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE needs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenants(id), signal_id uuid REFERENCES signals(id), company_id uuid REFERENCES companies(id), product_category text NOT NULL, specification jsonb NOT NULL);
CREATE TABLE offers (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenants(id), company_id uuid REFERENCES companies(id), product_category text NOT NULL, regions jsonb NOT NULL DEFAULT '[]', capability jsonb NOT NULL);
CREATE TABLE relationships (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenants(id), from_company_id uuid REFERENCES companies(id), to_company_id uuid REFERENCES companies(id), kind text NOT NULL, evidence jsonb NOT NULL DEFAULT '[]');
CREATE TABLE evidence (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenants(id), subject_type text NOT NULL, subject_id uuid NOT NULL, url text NOT NULL, claim text NOT NULL, observed_at timestamptz NOT NULL, content_hash text);
CREATE TABLE verifications (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenants(id), subject_type text NOT NULL, subject_id uuid NOT NULL, status text NOT NULL, checks jsonb NOT NULL, unknowns jsonb NOT NULL, verified_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE matches (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenants(id), signal_id uuid REFERENCES signals(id), need_id uuid REFERENCES needs(id), offer_id uuid REFERENCES offers(id), score integer NOT NULL CHECK (score BETWEEN 0 AND 100), rationale jsonb NOT NULL, brief text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE opportunities (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenants(id), match_id uuid REFERENCES matches(id), stage text NOT NULL DEFAULT 'human_review', both_interested boolean NOT NULL DEFAULT false, commercial_progression text);
CREATE TABLE conversations (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenants(id), opportunity_id uuid REFERENCES opportunities(id), channel text NOT NULL, state text NOT NULL, external_ref text);
CREATE TABLE deals (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenants(id), opportunity_id uuid REFERENCES opportunities(id), status text NOT NULL, value jsonb);
CREATE TABLE agent_runs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenants(id), desk deal_desk NOT NULL, objective text NOT NULL, status text NOT NULL, log jsonb NOT NULL DEFAULT '[]', started_at timestamptz NOT NULL, completed_at timestamptz);
CREATE TABLE approval_actions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenants(id), opportunity_id uuid REFERENCES opportunities(id), action_type text NOT NULL, status approval_status NOT NULL DEFAULT 'pending', payload jsonb NOT NULL DEFAULT '{}', reviewed_by text, reviewed_at timestamptz);

-- Apply PostgreSQL row-level security policies before any client tenant is onboarded.
